/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const computed: typeof import('vue')['computed']
  const defineStore: typeof import('pinia')['defineStore']
  const onMounted: typeof import('vue')['onMounted']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const ref: typeof import('vue')['ref']
  const router: typeof import('./src/router/index.js')['router']
  const storeToRefs: typeof import('pinia')['storeToRefs']
  const useHttp: typeof import('./src/helpers/httpHook.js')['useHttp']
  const usePagination: typeof import('./src/helpers/paginationHook.js')['usePagination']
  const useSortList: typeof import('./src/helpers/sortListHook.js')['useSortList']
  const watchEffect: typeof import('vue')['watchEffect']
}
