/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/Alert.vue')['default']
    Button: typeof import('./src/components/base/Button.vue')['default']
    Field: typeof import('./src/components/base/Field.vue')['default']
    Form: typeof import('./src/components/base/Form.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./src/components/base/Table.vue')['default']
  }
}
